version: '3'
services:
  synapse:
    environment:
      - SERVER_NAME=localhost
      - REPORT_STATS=yes
    build: docker-matrix
    command: 'generate'
    restart: on-failure
    container_name: synapse
    hostname: synapse
    ports:
      - "8008:8008"
      - "8448:8448"
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge